---
- name: Create VM from Template and Configure User
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware

  pre_tasks:
    - name: Load variables
      include_vars: variables.yaml

  tasks:
    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs | bool }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        name: "rhelai"
        template: "rhel86-tpl"
        folder: ""
        state: poweredon
        hardware:
          memory_mb: 4096
          num_cpus: 2
        disk:
          - size_gb: 20
            type: thin
            datastore: "{{ vcenter_datastore }}"
        networks:
          - name: "{{ vcenter_network }}"
            connected: true
        customization:
          hostname: "rhelai"
          domain: "example.com"
          dns_servers: ["8.8.8.8", "8.8.4.4"]
          timezone: "America/Bogota"
        wait_for_ip_address: true
      delegate_to: localhost
      register: vm_info

    - name: Wait for SSH to be available
      ansible.builtin.wait_for:
        host: "{{ vm_info.instance.ipv4 }}"
        port: 22
        delay: 30
        timeout: 300
        state: started

    - name: Add user 'app' with sudo privileges
      ansible.builtin.user:
        name: app
        password: "{{ 'mypassword' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
      become: true
      delegate_to: "{{ vm_info.instance.ipv4 }}"

    - name: Allow 'app' user to use sudo without password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/app"
        content: "app ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"
      become: true
      delegate_to: "{{ vm_info.instance.ipv4 }}"
