---
- name: Create VM in vSphere
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "your-vcenter-hostname"
    vcenter_username: "your-username"
    vcenter_password: "your-password"
    vcenter_datacenter: "your-datacenter"
    vcenter_cluster: "Cluster-1"
    vcenter_folder: "sandbox-xnbhd"
    vcenter_datastore: "workload_share_dwPsq"
    vcenter_network: "segment-sandbox-xnbhd (vcsnsx-vcs-shared-private)"
    validate_certs: false

  tasks:
    - name: Create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vcenter_folder }}"
        name: "reli"
        guest_id: "rhel9_64Guest"
        state: poweredon
        hardware:
          memory_mb: 2048
          num_cpus: 1
          scsi: paravirtual
        disk:
          - size_gb: 16
            type: thin
            datastore: "{{ vcenter_datastore }}"
        networks:
          - name: "{{ vcenter_network }}"
            type: vmxnet3
            connected: true
        wait_for_ip_address: false
      delegate_to: localhost
