---
- name: Extract info from VM
  hosts: localhost
  become: false
  gather_facts: true
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: variables.yaml
  tasks:
    - name: get vm info
      vmware_guest_info:
        hostnane: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ vcenter_vm_name }}"
      register: details

    - name: print vm info
      ansible.builtin.debug:
        var: details
