---
- name: Extract info from VM
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware

  pre_tasks:
    - name: Load variables
      include_vars: variables.yaml

  tasks:
    - name: Get VM info
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ vcenter_validate_certs | bool }}"
        name: "{{ vcenter_vm_name }}"
      delegate_to: localhost
      register: details

    - name: Print VM info
      ansible.builtin.debug:
        var: details
